language: php

php:
- 7.1

before_script:
- composer install --no-interaction

script:
- vendor/bin/phpunit tests --bootstrap tests/bootstrap.php --configuration phpunit.xml.dist --coverage-clover clover.xml
